# Generated by Django 3.1.7 on 2021-03-14 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_de_categoria', models.CharField(max_length=100, unique=True, verbose_name='nombre de categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_de_la_Marca', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_del_Producto', models.CharField(max_length=75)),
                ('Codigo_del_Producto', models.IntegerField()),
                ('Fecha_de_vencimiento', models.DateTimeField()),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.categoria')),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.marca')),
            ],
        ),
    ]
